import { Theme } from '@rainbow-me/rainbowkit';

export const ModalConnectTheme: Theme = {
  blurs: {
    modalOverlay: '0px',
  },
  colors: {
    accentColor: '...',
    accentColorForeground: 'rgba(0,212,255,1)',
    actionButtonBorder: '',
    actionButtonBorderMobile: '...',
    actionButtonSecondaryBackground: '',
    closeButton: '#eff3fb',
    closeButtonBackground: '#273550',
    connectButtonBackground: '',
    connectButtonBackgroundError: '',
    connectButtonInnerBackground: '',
    connectButtonText: '#eff3fb',
    connectButtonTextError: '',
    connectionIndicator: 'rgba(0,212,255,1)',
    downloadBottomCardBackground: '',
    downloadTopCardBackground: '',
    error: '...',
    generalBorder: '#273550',
    generalBorderDim: '',
    menuItemBackground: '#273550',
    modalBackdrop: '#0000004d',
    modalBackground: '#162239',
    modalBorder: '#273550',
    modalText: '#eff3fb',
    modalTextDim: '',
    modalTextSecondary: '#b7becb',
    profileAction: '#09162e',
    profileActionHover: '#273550',
    profileForeground: '',
    selectedOptionBorder: '',
    standby: '',
  },
  fonts: {
    body: '...',
  },
  radii: {
    actionButton: '10px',
    connectButton: '10px',
    menuButton: '10px',
    modal: '10px',
    modalMobile: '...',
  },
  shadows: {
    connectButton: '...',
    dialog: '...',
    profileDetailsAction: '...',
    selectedOption: '...',
    selectedWallet: '...',
    walletLogo: '...',
  },
};
